import 'package:busca_ao_tesouro/models/fases_enum.dart';

class Fase {

FaseE id;
String title;
String message;
String password;
String tip;
bool enabled;
bool unlocked;

Fase( { this.id, this.title, this.message, this.tip,
       this.password, this.enabled, this.unlocked}); 

}

// Lista de fases
List<Fase> fases = [
  Fase( id: FaseE.inicial,
        title: 'Bem vindo',
        message: 'Este é um jogo criado específicamente para testar seus conhecimentos sobre si.\n Mas, saiba que precisará da ajuda dos seus amigos é claro.\n O bom de tudo isso é que ao chegar ao final você encontrará seu tesouro.\n Portanto, seja persistente nas suas respostas e faça de tudo para vencer cada desafio.\n Regra: Para avançar, a cada fase você deve seguir as dicas descritas nos textos.',
        tip: 'Use uma das senhas mais óbvias do mundo, com 4 digitos, que é odiada por todos os gestores de segurança em TI',
        password: '0000',
        enabled: true,
        unlocked: true ),
  Fase( id: FaseE.desafioBiblia,
        title: 'Bíblia',
        message: 'Loren ipsum como informações sobre onde deve-se buscar pistas adicionais.\nSeguindo as instruções que estão contidas no último pergaminho você poderá chegar ao objetivo desejado e avançar para a próxima etapa deste jogo.',
        password: '1234',
        enabled: true,
        unlocked: false ),
  Fase( id: FaseE.desafioIdadeDosPais,
        title: 'Seus pais',
        message: 'A história foi mais ou menos assim: - Esses dois se conheceram e você nasceu',
        password: '1234',
        tip: 'Nos objetos de uso pessoal de seu pai você poderá encontrar a senha que precisa. Examine com cuidado!',
        enabled: true,
        unlocked: false ),
  Fase( id: FaseE.desafioDatasAvos,
        title: 'Datas avós',
        message: 'Loren ipsum como informações sobre onde deve-se buscar pistas adicionais',
        password: '1234',
        enabled: true,
        unlocked: false ),
 Fase( id: FaseE.desafioIdadeAmigos,
        title: 'Idade amigos',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),        
 Fase( id: FaseE.desafioEnigmaMusicaRacionais,
        title: 'Conhece música?',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
 Fase( id: FaseE.desafioPistaria,
        title: 'Pistaria',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
 Fase( id: FaseE.desafioMassaMolhoBranco,
        title: 'Sabe cozinhar?',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
 Fase( id: FaseE.desafioPesoLivro,
        title: 'Estudou direito?',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
Fase( id: FaseE.desafioPlacas,
        title: 'Carros tem placas?',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
Fase( id: FaseE.desafioInformatica,
        title: 'A1Z26',
        message: 'Este código é um padrão de ocultação de informações. Apesar do nome longo o funcionamento é simples conhecido\n ',
        tip: '5149 - Encontre em algum equipamento a palavra que precisa ser decifrada e coloque aqui a sequencia de dígitos, respeitando os padrões que você está usando até o momento.',
        password: '5149',
        enabled: true,
        unlocked: false ),
Fase( id: FaseE.desafioTapaTapa,
        title: 'Tapa, tapa, tapa, tapa!',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
Fase( id: FaseE.desafioParaquedismo,
        title: 'Lembra quando você saltou de paraquedas?',
        message: 'Na vida, algumas pessoas fazem muitas coisas.\n ',
        tip: 'Procure dados dentro do material de um evento que você participou.',
        password: '1234',
        enabled: true,
        unlocked: false ),              
Fase( id: FaseE.desafioQuebraCabeca,
        title: 'Gosta de jogos',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
Fase( id: FaseE.desafioFogo,
        title: 'Fogo do fogão',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),
Fase( id: FaseE.desafioDado,
        title: 'Doze ou dose?',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),                        
Fase( id: FaseE.desafioAmor,
        title: 'Não sei',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),        
 Fase( id: FaseE.faseFinal,
        title: 'Parabéns!',
        message: 'Parabéns, graças a você e sua equipe terem cumprido os desafios, estão bem perto de encontrarem o tesouro.\n ',
        tip: 'Esta é sua última dica e que bom que você chegou até aqui. Basta agora você procurar o local onde tem uma chave elétrica, tipo (I/O), que liga um motor que ajuda a manter uma das diversões da sua casa\nAo fazer isso, você finalmente encontrará o verdadeiro mapa que te levará até o seu tesouro.',
        password: '1234',
        enabled: true,
        unlocked: false ),        
];

